FROM node:16.15

# Create app directory
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
ENV TZ=Africa/Tunis
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN export NODE_ENV=production
# Bundle app source
COPY . .
EXPOSE 5004
CMD [ "node", "server.js" ]
