// AUTH //
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOAD_EN = "AUTH_LOAD_EN";
export const AUTH_LOAD_DIS = "AUTH_LOAD_DIS";
export const AUTH_RESET_STATE = "AUTH_RESET_STATE";
export const GET_DEVELOPERS_SUCCESS = "GET_DEVELOPERS_SUCCESS";
export const GET_DEVELOPERS_FAILED = "GET_DEVELOPERS_FAILED";
export const GET_MANAGERS_SUCCESS = "GET_MANAGERS_SUCCESS";
export const GET_MANAGERS_FAILED = "GET_MANAGERS_FAILED";

// PROJECTS //
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILED = "GET_PROJECT_FAILED";
export const GET_PROJECT_EN = "GET_PROJECT_ENABLE";
export const GET_PROJECT_DIS = "GET_PROJECT_DISABLE";

export const CLOSE_PROJECT_SUCCESS = "CLOSE_PROJECT_SUCCESS";
export const CLOSE_PROJECT_FAILED = "CLOSE_PROJECT_FAILED";
export const CLOSE_PROJECT_EN = "CLOSE_PROJECT_ENABLE";
export const CLOSE_PROJECT_DIS = "CLOSE_PROJECT_DISABLE";

// ADD PROJECT //
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILED = "CREATE_PROJECT_FAILED";
export const CREATE_PROJECT_LOAD_EN = "CREATE_PROJECT_LOAD_EN";
export const CREATE_PROJECT_LOAD_DIS = "CREATE_PROJECT_LOAD_DIS";
export const RESET_PROJECT = "RESET_PROJECT";

// TASKS //
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAILED = "GET_TASKS_FAILED";
export const GET_TASKS_EN = "GET_TASKS_EN";
export const GET_TASKS_DIS = "GET_TASKS_DIS";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILED = "CREATE_TASK_FAILED";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILED = "UPDATE_TASK_FAILED";
export const UPDATE_TASK_ENABLE = "UPDATE_TASK_ENABLE";
export const UPDATE_TASK_DISABLE = "UPDATE_TASK_DISABLE";